In [1]:

# Running this cell will set up auto-grading
# It might take a while to execute.

# Please fill in the MIT id form that appears below. You only need to do this once.

Pkg.rm("Homework")
Pkg.clone("git://github.com/shashi/Homework.jl.git")

using Homework

Homework.show_mit_form()

INFO: Removing Homework (unregistered)
INFO: Cloning Homework from git://github.com/shashi/Homework.jl.git
INFO: Computing changes...
INFO: No packages to install, update or remove


and contains known security vulnerabilities. Please upgrade to a
more recent version.


Html("<script>IPython.notebook.kernel.comm_manager.comms[\"2262d6d0-8302-4c92-9c12-4c382078e0a8\"].then(\n    function (comm) {\n        comm.send({\n            cookie: document.cookie,\n            host: IPython.notebook.metadata.homework.host,\n            course: IPython.notebook.metadata.homework.course,\n            mode: IPython.notebook.metadata.homework.mode,\n            problemset: IPython.notebook.metadata.homework.problemset\n        })\n    }\n)</script>")

Loading...

In [ ]:
# After you've answered the pset, Check your progress by running this cell.
Homework.progress()

## Problem 1a. (2 pts)  PIVOTS AND FREE VARIABLES <br>

Suppose column 1 + column 3 + column 5 = 0 in a 4 by 5 matrix with four pivots. <br>
Which column is sure to have no pivot? <br>

Answer should be a column number such as 2.

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

Which variable is free? <br>

Answer should be a variable number such as 2.

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

## 1b. (1pt) SPECIAL SOLUTIONS <br>
Suppose column 1 + column 3 + column 5 = 0 in a 4 by 5 matrix with four pivots. What are the special solutions? <br>

**Instructions**
- If there are none write the empty vector `[]`. <br>
- If there is one, write a Julia vector. Example: `[a b c]`
- If there is more than one, write a Julia matrix. Example: `[ [a b c]; [d e f] ]`



Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

## Problem 2. (4 pts) REDUCED FORMS <br>

The reduced form R of a 3 by 3 matrix with randomly chosen entries is almost sure to be_______________. <br>

Enter the solution as a Julia matrix of Int64's. Example:  [[1 2 3];[4 5 6]]

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

The reduced form R of a 4 by 3 matrix with randomly chosen entries is almost sure to be______________. <br>

Enter the solution as a Julia matrix of Int64's.

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

## Problem 3. (6 pts) REDUCED FORMS OF BLOCK MATRICES <br>
Find the reduced echelon form R for A and each of the block matrices B and C:

$A= \begin{pmatrix}0 & 0 & 0 \\ 0 & 0 & 3 \\ 2 & 4 & 6 \end{pmatrix} \hspace{.3in}$ 
$B= \begin{pmatrix} A & A \end{pmatrix} \hspace{.3in}$ 
$C= \begin{pmatrix} A & A \\ A & 0 \end{pmatrix}$ <br> <br>

$A_{reduced}$ =   <br> 
Enter as a Julia Int64 matrix.  Example [[1 2 3];[4 5 6]] or  <br>
[1 2 3 <br>
 4 5 6] <br>
 
 Note: while rref will compute the answer, it won't be Int64, it will be Float64. It can be converted,
 but we really want you to do this by hand and just type in the answer.

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

$B_{reduced}$ =   <br>
Enter as a Julia Int64 matrix.  Example [[1 2 3];[4 5 6]] or  <br>
[1 2 3 <br>
 4 5 6] <br>

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

$C_{reduced}$ =   <br>
Enter as a Julia Int64 matrix.  Example [[1 2 3];[4 5 6]] or  <br>
[1 2 3 <br>
 4 5 6] <br>

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

## Problem 4. (2 pts) COMPLETE SOLUTION <br>

Construct a 2 by 3 system Ax=b with particular solution $x_p$=(2,4,0) and has as homogeneous solution $x_n$ = any multiple of (1,1,1). <br>

Write Julia code such as these three lines: <br>
A = ????     (The matrix A as in  A = [[1 2 3];[4 5 6 ]] ) <br>
b = ???      (The vector b as in  b=[1, 2, 3]) <br> <br>
test = A * [1,1,1] == [0,0]  &&  b==A  * [2,4,0] && rank(A) > 0 

The goal is to find A and b so that test yields true.

In [11]:
A =   # something like [[1 2 3];[4 5 6 ]]
b =   #something like [1, 2, 3]


test = A*[1,1,1] == [0,0] && b==A * [2,4,0] && rank(A) > 0

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

## Problem 5a. (4 pts) FULL RANK

These questions are about a "full rank" r=m or r=n matrix. Say the matrix has m=6 rows and n=4 columns. <br>

The largest possible rank of a 6 by 4 matrix is (enter an integer such as 0, 1, 2, ...)

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

There is a pivot in every <span style="border-bottom: 2px solid black; padding-left: 150px">&nbsp;</span> of U and R. <br>

1. row <br>
2. column <br>
3. entry <br>
4. cannot be determined from information given  <br>
Answer: 1, 2, 3, or 4

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

The solution to Ax=b <span style="border-bottom: 2px solid black; padding-left: 150px">&nbsp;</span>. <br>

1. always exists, and is unique 
2. always exists, but is not unique 
3. does not always exists, but is unique when it does 
4. does not always exists, and is not unique when it does <br>
Answer: 1, 2, 3, or 4


Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

The nullspace of A is <span style="border-bottom: 2px solid black; padding-left: 150px">&nbsp;</span> . <br>

1. ∅  
2. 0-dimensional 
3. 1-dimensional 
4. 2-dimensional 
5. 4-dimensional <br>
Answer: 1, 2, 3, 4, or 5

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

## 5b. (2 pts)  FULL RANK 2

Give an example of a 6 by 4 matrix with full rank.

Write a Julia matrix, perhaps in the form <br>
```
A= [a b c d
    e f g h
    i j k l
    m n o p
    q r s t]
```
and then type

`rank(A)`
   



Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

## 6a. (3 pts) SPACES OF MATRICES

What subspace of 3 by 3 matrices is spanned (take all combinations) by the following matrices? <br>

### I. The invertible matrices

1.The whole set of matrices. <br>
2 The set of invertible matrices. <br>
3.The set of matrices with at least one non zero entry. 

Choose a number: 1,2, or 3


Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

### II. The Rank One matrices <br>

1. The set of rank one matrices. <br>
2. The set of rank three matrices.<br>
3. The whole set of matrices

Choose a number: 1,2, or 3

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

### III. The identity matrix.

1. The set of diagonal matrices. <br>
2. The whole set of matrices.  <br>
3. The set of diagonal matrices with the same entry on the diagonal

Choose a number: 1,2, or 3

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

## 6b. (3 pts) SUM OF RANK ONE MATRICES

Suppose $A$ is the sum of two matrices of rank one: $A=uv^T+wz^T$.

### I. Which vectors span the column space of A?

 1. The linear combinations of v$_i$u+z$_i$w, where i=1,2,....  <br>
 2. The vectors u and w.  <br>
 3. The vectors v and w.  <br>
 4. The linear combinations of  u$_i$v$^T$+w$_i$v$^T$, where i=1,2,...
 
 Choose a number: 1,2,3, or 4

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

II. Which vectors span the row space of A?

1. The linear combinations of  v$_i$u+z$_i$w, where i=1,2,...  <br>
2. The vectors z and w.  <br>
3. The vectors v and z. <br>
4. The linear combinations of u$_i$v$^T$+w$_i$v$^T$, where i=1,2,...

Choose a number: 1,2,3, or 4

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

III. The rank is less than 2 if and only if <span style="border-bottom: 2px solid black; padding-left: 150px">&nbsp;</span>.

1. u and w are dependent or v and z are dependent <br>
2. one of the four vectors is zero  <br>
3. u and w are dependent <br>
4. u and z are dependent or v and w are dependent

Choose a number: 1,2,3, or 4

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

## 7. SPECIAL SOLUTIONS

**7a. (2 pts)**
For the matrix 
$A=\begin{pmatrix}
1 & 2 & 2 & 4 & 6 \\
1 & 2 & 3 & 6 & 9 \\
0 & 0 & 1 & 2 & 3
\end{pmatrix}$
 find a special solution for every free variable. 
(Set one free variable to 1. Set the other free variables to zero.)

Enter the special solutions by columns `[[a,b,c,d,e] [f,g,h,i,j] [k,l,m,n,o]]` in order of the free variables.
(If you see bounds error, make sure you put a space between right brackets and left brackets)

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

For the matrix
$B=\begin{pmatrix}
2 & 4 & 4 \\
0 & 4  & 4\\
0 & 8 & 8
\end{pmatrix}
$
find a special solution for every free variable. (Set one free variable to 1. Set the other free variables to zero.)

Enter the special solutions  more or less as above.

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

**7b (3 pts.) RREF and Nullspace**

Find the reduced row echelon form $R_B$ of
$B=\begin{pmatrix}
2 & 4 & 4 \\
0 & 4  & 4\\
0 & 8 & 8
\end{pmatrix}
$

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

Find the reduced row echelon form $R_A$ of
$A=\begin{pmatrix}
1 & 2 & 2 & 4 & 6 \\
1 & 2 & 3 & 6 & 9 \\
0 & 0 & 1 & 2 & 3
\end{pmatrix}
$

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

Is the nullspace of $R_A$ equal to the nullspace of A? <br>
Type true or false

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

**7c (4 pts.) PIVOTS AND FREE VARIABLES**   (type `true` or `false` for each of these problems)

True or False.

A square matrix has no free variables


Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

An invertible matrix has no free variables

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

An m by n matrix has no more than n pivot variables


Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

An m by n matrix has no more than m pivot variables

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

## 8 . (3 Pts.) NULLSPACE AND SPECIAL SOLUTIONS  

The JULIA command rref(A) finds the reduced echelon form of a matrix A. <br>
Okay to type  <br>
? rref
but it won't tell you much.

For each matrix equation Ax=0, use rref to determine the number of special solutions, which is equal to the dimension of the nullspace.

rand(9,9)x = 0 <br>
ones(9,9)x = 0 <br>
[1 -2 -1 1 0 -1; 2 1 2 3 1 -1; -1 -2 1 -3 0 -3]x = 0

You can use rref to determine the dimension of the nullspace. Recall that a point has dimension 0, a line dimension 1, and plane dimension 2.

In [39]:
rref(rand(9,9))

9x9 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [36]:
nullspace_dimension = ?

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

In [13]:
rref(ones(9,9))

9x9 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [37]:
nullspace_dimension = ?

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

In [45]:
rref([1 -2 -1 1 0 -1; 2 1 2 3 1 -1; -1 -2 1 -3 0 -3])

3x6 Array{Float64,2}:
 1.0  0.0  0.0   1.625  0.25   0.0
 0.0  1.0  0.0   0.5    0.0    1.0
 0.0  0.0  1.0  -0.375  0.25  -1.0

In [54]:
nullspace_dimension = ?

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

## 9 . (2 pt.) NULLSPACE
In Julia set
` v=[1, 2, 3]`  then
` w=[2, 3, 4]` and
` A=zeros(3,3)`

Then create the matrix 
$A=\begin{pmatrix} 1 & 2 & 3 \\2  & 3 & 4 \\ 3 & 4 & 5 \end{pmatrix}$ using Julia's  column assignment
commands.

In other words 

`A[:,1]` =  (first column in terms of v and w) 
`A[:,2]` =  (second column in terms of v and w) 
`A[:,3]` =  (third column in terms of v and w) 

Conclude with the rref(A).  There probably should be 7 lines of code all together.

In [40]:
A=zeros(3,3)
v=[1,2,3]
w=[2,3,4]
A[:,1]=?
A[:,2]=?
A[:,3]=?
display(A)
rref(A)

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

## 10 .  (3 pts.) MORE EXERCISE WITH RREF

Suppose that R is the reduced echelon form of a 4 by 5 matrix A.

$R = rref(A) =
\begin{pmatrix} 1 & 3 & 0 & 1 & -2 \\
0 & 0 & 1 & 2 & 4 \\
0 & 0 & 0 & 0 & 0 \\
0 & 0 &0& 0 & 0
\end{pmatrix} $

If $v=[1,2,3,4]$ is the first column of $A$ and  $w=[5,6,7,8]$ is the third column of $A$,
what is $A$?  Okay to use Julia to compute. We'll start you off.

In [53]:
v=[1,2,3,4]
w=[5,6,7,8]

# Edit the line that follows, to get A.

4-element Array{Int64,1}:
 5
 6
 7
 8

In [51]:
A = [v ?v w v+?w ?v+?w]

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

## 11 . (3 pts.) STATISTICS ON RANDOM MATRICES

We did a diffusion problem last week that showed how useful Julia (or MATLAB) can be in testing and exploring ideas in applied math problems. This week we'll see how useful Julia(or MATLAB) can be in experimenting to create conjectures about mathematics ideas.

We've seen that on average, a random matrix is invertible. But what if the random matrix has entries that are either 0 or 1 with equal probability? What is the probability that a 5 by 5 matrix whose entries are all zeros or ones is singular? And what is the average number of pivot columns? That is what you will find out in this exercise.


To create a random integer matrix whose entries are either 0 or 1, you can use the Julia command rand(0:1,5,5);. To find the number of pivot columns of a matrix R, use the Julia command rank(R).

To create a conjecture on the probability that such a matrix is singular, we are going to want to collect a lot of data. That means that we want to generate many many of these matrices. You may want to start small, say 5 or 10, but the you might what to test your conjectures for even larger numbers, say 100, 1000, or 10000. 

There is some  code created for you below. 




In [41]:
function randstats(num,n)
 ranks = [ rank(rand(0:1,n,n)) for i=1:num]  # Run num experiments and build a vector of ranks
 mean(ranks), mean(ranks.< n)
end

randstats (generic function with 1 method)

In [47]:
num = 100000;  # Number of random trials (100,000 takes 2 seconds, your matlab friends were told to stay less than 10,000)
n = 5  # Size of matrix
@time randstats(num,n)

elapsed time: 24.997667196 seconds (12878368472 bytes allocated, 39.64% gc time)


(4.272566,0.626207)

In [50]:
# Enter what you see  (avg number of pivots, probability of being singular)
# in the format [a.b,c.d] where you rounded the answer to one decimal place.
# a or c may be 0
# make sure you have converged

# We can't test this, but think about the answer, and decide if you are surprised
# or not.  Maybe play with some other numbers for your own amusement.  



Write your answer here as a vector, with floating point numbers rounded to 1st decimal place

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

## 12 . (3 pts.)  MORE RANDOM MATRICES  

We've looked at random matrices whose entries are 0 or 1. But how does size effect the rank and the probability of being singular? Repeat the previous exercise  for 10 by 10 matrices with entries that are 0 or 1.



To create a conjecture on the probability that such a matrix is singular, we are going to want to collect a lot of data. That means that we want to generate many many of these matrices. 



If you enjoyed this problem, you may be interested in looking at more data. Here are a few ideas to get your started.

You can explore the probability of singularity and the average number of pivots for different sizes of random matrices.  Can you determine how this probability depends on the size of the matrix?
You might try to find the probability of a 10 by 10 random matrix with entries 0 or 1 has rank 10, 9, 8, 7 etc. You can check your probabilities against the expected value to see if your probabilities match your observations.
You might try to connect these probabilities with determinant formulas to see if you can predict the numbers from other formulas and prove a relationship.
Happy explorations!

( guess what happens as n$\rightarrow \infty$, but only run up to 80, we have limited free cycles so please 
be kind)

In [43]:
nvalues = [5,10,20,40,80]
for n in nvalues
  
@time println("n:", n,  ":", randstats(500,n))
end


n:5:(4.232,0.652)
elapsed time: 0.022301843 seconds (6827680 bytes allocated)
n:10:(9.718,0.27)
elapsed time: 0.018120023 seconds (8616040 bytes allocated)
n:20:(19.996,0.004)
elapsed time: 0.048506671 seconds (14090232 bytes allocated)
n:40:(40.0,0.0)
elapsed time: 0.1877261 seconds (29689376 bytes allocated, 17.51% gc time)
n:80:(80.0,0.0)
elapsed time: 0.803544689 seconds (80264872 bytes allocated, 9.96% gc time)


Suppose n were too large to run, say `n=10^100`.  (Do not try to run, please!) 
Take a guess at the mean number of pivots divided by n.  Take a guess at the probability
of singularlity.  Type your answer in the format `[a.b, c.d]`

Html("<script></script>")

Button{Nothing}([Input{Nothing}] nothing,"Submit \ubb",nothing)

In [ ]:
Homework.progress()