Exam 3 practice

Do go over homeworks and notes as well.

We will perform Julia computations for you.  You will not need the computer to solve any problems. 

(1) Let $E_n$ by the symmetric tridiagonal ones matrix.  For example

In [15]:
using LinearAlgebra
E(n) = SymTridiagonal(ones(Int,n),ones(Int,n-1),ones(Int,n-1))

E(n) = Tridiagonal(ones(Int,n-1),ones(Int,n),ones(Int,n-1))
inv(E(7))

7×7 Array{Float64,2}:
  1.0   0.0  -1.0   1.0   0.0  -1.0   1.0
  0.0   0.0   1.0  -1.0   0.0   1.0  -1.0
 -1.0   1.0   0.0   0.0   0.0   0.0   0.0
  1.0  -1.0   0.0   1.0   0.0  -1.0   1.0
  0.0   0.0   0.0   0.0   0.0   1.0  -1.0
 -1.0   1.0   0.0  -1.0   1.0   0.0   0.0
  1.0  -1.0   0.0   1.0  -1.0   0.0   1.0

In [2]:
E(9)^(-1)

9×9 Array{Float64,2}:
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

(1a) When n=5, column 1 plus column 4 is the "ones" vector.  Find two other columns that add to the ones vector.
What is the determinant of $E_5$? and provide one  eigenvalue and corresponding eigenvector of $E_5$.

(1b) Is $E_5$ diagonalizible?  Why or why not?

(1c) Is the cofactor matrix of $E_n$ symmetric for all n?  Why or why not?

In [4]:
E(6)

6×6 SymTridiagonal{Int64,Array{Int64,1}}:
 1  1  ⋅  ⋅  ⋅  ⋅
 1  1  1  ⋅  ⋅  ⋅
 ⋅  1  1  1  ⋅  ⋅
 ⋅  ⋅  1  1  1  ⋅
 ⋅  ⋅  ⋅  1  1  1
 ⋅  ⋅  ⋅  ⋅  1  1

(1d) What is the determinant of $E_6$? What is the volume of the image of the unit cube: <br>
    $\{ E_6x, x\in R^6,  0 \le x_i \le 1 \}$

In [2]:
E(8)

8×8 SymTridiagonal{Int64,Array{Int64,1}}:
 1  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 1  1  1  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  1  1  1  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  1  1  1  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  1  1  1  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  1  1  1  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  1  1  1
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  1

(1e) It turns out that for $n=2,5,8,11,14$ $E_n$ is singular.  Find an eigenvector of $E_n$ for all such $n$.

(1f) What is the sum of the eigenvalues of $E_n$ for all n?

When n=7, we can compute $E_n^2$:

In [5]:
E(7)^2

7×7 Array{Int64,2}:
 2  2  1  0  0  0  0
 2  3  2  1  0  0  0
 1  2  3  2  1  0  0
 0  1  2  3  2  1  0
 0  0  1  2  3  2  1
 0  0  0  1  2  3  2
 0  0  0  0  1  2  2

(1g) What is the sum of the squares of the eigenvalues of $E_8$? Generalize for all n. Explain.

In [8]:
inv(E(7))

7×7 Array{Int64,2}:
  1   0  -1   1   0  -1   1
  0   0   1  -1   0   1  -1
 -1   1   0   0   0   0   0
  1  -1   0   1   0  -1   1
  0   0   0   0   0   1  -1
 -1   1   0  -1   1   0   0
  1  -1   0   1  -1   0   1

(1h) Use the above computation to say what is the sum of the reciprocals of the eigenvalues of $E_7$?

(2a) What is the determinant of $A = \left(\begin{array}{rrrrr}1&0&0&0&0\\- a&1&0&0&0\\0&- b&1&0&0\\0&0&- c&1&0\\0&0&0&- d&1\end{array}\right)$?

(2b) What are the eigenvalues of $A$?

(2c) Give an example (by picking a,b,c,d) where $A$ is diagonalizible, and another example where it is not.

(2d) What is the first column of the inverse of $A$ using determinants and cofactors? (This question should not require much pencil and paper work.)

(3) Let P be the permutation matrix
$$ \begin{pmatrix} . &1 & . & .\\ . & . & 1 & . \\ . & . &  . & 1 \\ 1 & . & . & .\end{pmatrix}.$$

(3a) What is $P^4$? 

(3b) It turns out $P$ has four distinct eigenvalues.  Use your answer to (3a) to say what they are. 

(3c) Does $P$ have four distinct singular values?

(3d) Find an eigenvector of $P$.

(3e) Compute det(P$\pm$I)

(4) A matrix can be factored as $A=X\Lambda X^{-1}$.

(4a) This matrix is i)definitely, ii)possibly, iii)definitely not invertible. (pick one)

(4b) This matrix i)definitely ii)possible, iii) definitely not diagonalizible (pick one)

(4c) Find an eigen factorization for $(A-I)(A-2I)$.

(4d) Find a factorization for  $(𝐴−\lambda_1 I)\ldots(𝐴−\lambda_n𝐼)$ and then put this matrix in simplest form .

(4e) Suppose the largest eigenvalue has absolute value less than 1.  Then the matrix
$A-I$ is i) definitely ii) possibly iii)definitely not invetible. (pick one)

(4f) Suppose the largest eigenvalue has absolute value exactly 1.  Then the matrix
$A-I$ is i) definitely ii) possibly iii)definitely not invetible. (pick one)

(5) The image of the unit cicle for a certain 2x2 symmetric matrix is an ellipse with semiaxes
 1806 and 2019. What are all the possibilities for the eigenvalues of this matrix?

(6) True or false.  A matrix with real eigenvalues and eigenvectors must be symmetric.  Explain?

(7) A matrix is symmetric and orthogonal.  What are the possible eigenvalues?

(8) A matrix is a projection matrix and orthogonal.  What are the possible matrices?

(9) A matrix has all of its eigenvalues $0$.  The set of matrices similar is i)infinite ii)possibly finite iii)must be finite.  (Pick the best answer)

(10) True or false.  The absolute value of the eigenvalues of a matrix $A$ always describe the semi-axes of
the image of the unit ball under $A$.

(11) Suppose that all the nonzero eigenvalues of $A$ are distinct, and the dimension of the nullspace of $A$ is equal to the number of $0$ eigenvalues.  Why is $A$ diagonalizible?

(12) A matrix has all eigenvalues real and negative.  What can you say about the matrix exp(At) as $t\rightarrow \infty$?