Problem 1.  Suppose Q is n x n  orthogonal (meaning square with orthonormal columns) and A is n x n. What are the possible determinants |QA| in terms of |A|?

Problem 2. Suppose Q is n x n orthogonal and A is n x m.  What are the possible sum of squares of all elements of QA in terms of the sum of squares of all elements in A.

Problem 3. Let A=UΣVᵀ be an SVD of A.  What is the product of the diagonal elements of Σ in terms of A?

Problem 4.  Let A be as in Problem 3, what is the sum of squares of the singular values in terms of A?

Problem 5. Let A be as in Problem 3.  What is the sum of the diagonal elements of AᵀA in terms of the singular values?  What about the sum of the diagonal elements of AAᵀ?

Problem 6.  A Hadamard matrix H is a matrix with entries ±1 and orthogonal columns. What is the determinant of H as a function of n?

Problem 7.  Consider the vectors x such that w ⋅ x = 0.  These vectors are in the left nullspace of w thought of as an n x 1 matrix.  Describe all vectors perpendicular to such x.  Let b be any scalar, find the distance from the hyperplane (not throught the origin)  w ⋅ x = b to the hyperplane (not through the origin) w ⋅ x = - b. (This distance is used in the terribly named and I believe hardly used machine learning approach known as Support Vector Machines.)

Problem 8. If P is a projection matrix.  What are the possible values of |P|?

Problem 9. Find a 3x3 matrix with entries 0 and 1 with determinant  -2,-1,0, and 1,2. (Okay to use rand(0:1,3,3) if it helps)

Problem 10. If A is 3x3 with entries 0 and 1, if A is nonsingular, and you perform row eliminations what are the possible entries of U in PA=LU? Why can't |A| be greater than 2?

Problem 11.  What is the pattern in the formula for the determinant of S(n) given by the Julia code below? You may see it by inspecting, but ultimately you should figure it out by math. (Based on GS Problem 21 on p. 269.)

In [42]:
S(n) = SymTridiagonal( 3*ones(Int,n), ones(Int,n-1))

S (generic function with 1 method)

In [43]:
S(5)

5×5 SymTridiagonal{Int64}:
 3  1  ⋅  ⋅  ⋅
 1  3  1  ⋅  ⋅
 ⋅  1  3  1  ⋅
 ⋅  ⋅  1  3  1
 ⋅  ⋅  ⋅  1  3

In [44]:
[det(S(n)) for n=1:6]

6-element Array{Int64,1}:
   3
   8
  21
  55
 144
 377

GS p257, Challenge Problem 39. <br>
Problem 12. If you know all 16 cofactors of a 4x4 invertible matrix A, how would you find A?

Problem 13.  Explain the pattern for det(M(n)) (the determinant of a cycle) given by the Julia Code Below.
What is M(n)^n?

In [102]:
M(n) = eye(Int,n)[:,[2:n;1]]

M (generic function with 1 method)

In [104]:
M(3)

3×3 Array{Int64,2}:
 0  0  1
 1  0  0
 0  1  0

In [105]:
M(4)

4×4 Array{Int64,2}:
 0  0  0  1
 1  0  0  0
 0  1  0  0
 0  0  1  0

In [106]:
[det(M(n)) for n=1:5]

5-element Array{Float64,1}:
  1.0
 -1.0
  1.0
 -1.0
  1.0