# 18.06 Fall 2018 pset 1 (in progress)
## (due Wednesday 2/14 at 10:55am by submitting pdf through [Stellar](https://stellar.mit.edu/S/course/18/sp18/18.06/) )

This problem set is in the form of a [Julia](http://julialang.org/) *notebook* (using the [Jupyter](http://jupyter.org/)/[IJulia](https://github.com/JuliaLang/IJulia.jl) browser-based interface to interactive programming).  We will be using the Julia language throughout the term for simple computational explorations — practical linear algebra is not about hand computations!

You can run this without installing anything by logging in at [JuliaBox](https://juliabox.com/).  Just download the notebook file (a `.ipynb` file) by clicking the download icon at the upper right, then drag it onto the JuliaBox dashboard to upload it there.

Some of the problems are pencil-and-paper (we just happen to use the notebook to describe them), and some of them require you to run the code in the notebook to see what happens and then explain it.  To **run the code** in an input cell, **just click on the cell and then type shift-return**; see also the "Help" menu in the notebook.  When you submit your pset, you may handwrite or type, but please look over and submit one clearly labeled pdf.  You may find
that the Jupyter Download-as-PDF or PrintPreview followed by the Browser Print button is cleaner.

## Problem 1

Which of these matrix functions  make sense (assume $m \ne n$)?
1. f(x) = W * x      (where W is an m x n matrix, x is a length n vector)
1. f(x) = W * x + b   (where W is an m x n matrix, x is a length n vector, b is a length n vector)
1. f(x) = W \* W * x (where W is an m x n matrix, x is a length n vector)
1. f(x) = W * x  + b (where W is an m x n matrix, x is a length n vector, b is a length m vector)
1. f(x) = x * W     (where W is an m x n matrix, x is a length n vector)
1. f(x) = sin.(W \* x) (where W is an m x n matrix, x is a length n vector and the "." means take the sine of element of the vector W*x)
1. f(x) = sin.(W) \* x  (where W is an m x n matrix, x is a length n vector)
1. f(x) = σ.(x) where (where σ is the [sigmoid](https://en.wikipedia.org/wiki/Sigmoid_function) function σ(t) = 1/(1+e$^{-t}$))

<br>
The "." is usually pronounced "dot" but if one thinks "point" one might remember it is a "pointwise" operation, i.e. applies seperately to every element.
<br><br><br><br><br><br><br>
Execute the commands in Julia to check your work.  While there will not be any computers on the exams, in the real world people check themselves all the time with a computer. (Shift +<enter> executes and moves to the next cell.)



In [ ]:
σ

In [282]:
m = 2
n = 4
W = rand(m,n)
x = rand(n)
bm = rand(m)
bn = rand(n); # final semicolon suppresses printing of output

In [284]:
W

2×4 Array{Float64,2}:
 0.735342  0.19322   0.93041   0.358573 
 0.253639  0.472581  0.545723  0.0131464

Notice W is a 2x4 arrray whose elements are Float64 (they have decimals) and it is a "2" dimensional **matrix**.

In [286]:
x

4-element Array{Float64,1}:
 0.183982
 0.276873
 0.458068
 0.122616

Notice x is a length 4 vector of Float64's and it is a "1" dimensional matrix. Humans often conflate a 4 vector with a 4x1 matrix.  Sometimes this is highly productive.  Julia usually makes the distinction between a 4 vector and a 4x1 matrix.

In [287]:
W*x

2-element Array{Float64,1}:
 0.658945
 0.4291  

In [289]:
W*x + bn

LoadError: DimensionMismatch("dimensions must match")

In [290]:
W*W*x

LoadError: DimensionMismatch("A has dimensions (2,4) but B has dimensions (2,4)")

In [292]:
W*x + bm

2-element Array{Float64,1}:
 0.962004
 0.62312 

In [293]:
x * W  

LoadError: DimensionMismatch("A has dimensions (4,1) but B has dimensions (2,4)")

In [296]:
sin.(W*x)

2-element Array{Float64,1}:
 0.612283
 0.416053

In [297]:
sin.(W) * x

2-element Array{Float64,1}:
 0.586927
 0.411561

In [304]:
σ.(W*x) # You can type \sigma+<tab> to get the greek letter sigma

2-element Array{Float64,1}:
 0.659023
 0.605659

σ goes from 0 to 1.  It is known as an activation function in machine learning.
You can get help by typing question mark and a function name

In [313]:
? σ

"σ" can be typed by \sigma<tab>

search: σ



```
σ(x) = 1 / (1 + exp(-x))
```

Classic [sigmoid](https://en.wikipedia.org/wiki/Sigmoid_function) activation function.

```
1 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀│
  │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡠⠔⠒⠉⠉⠀⠀│
  │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⣀⠤⠚⠁⠀⠀⠀⠀⠀⠀⠀│
  │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⡤⠊⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
  │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⢀⡔⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
  │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⡔⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
  │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⡔⠊⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
  │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
  │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⠜⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
  │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠜⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
  │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⠜⠁⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
  │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡠⠚⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
  │⠀⠀⠀⠀⠀⠀⠀⢀⡤⠒⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
  │⠀⠀⣀⣀⠤⠔⠊⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
0 │⠋⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
  -3                      0                      3
```


In [25]:
n = 1000 
m = Dense(identity, rand(n,n), zeros(n))

Dense(1000, 1000)

In [26]:
using BenchmarkTools

In [27]:
@benchmark m(x)

LoadError: DimensionMismatch("second dimension of A, 1000, does not match length of x, 400")

In [30]:
n = 10_000
m = Dense(identity, rand(n,n), zeros(n))
x = rand(n)
@benchmark m(x)

BenchmarkTools.Trial: 
  memory estimate:  156.41 KiB
  allocs estimate:  4
  --------------
  minimum time:     44.657 ms (0.00% GC)
  median time:      50.279 ms (0.00% GC)
  mean time:        50.410 ms (0.00% GC)
  maximum time:     60.930 ms (0.00% GC)
  --------------
  samples:          100
  evals/sample:     1

In [31]:
n = 20_000
m = Dense(identity, rand(n,n), zeros(n))
x = rand(n)
@benchmark m(x)

BenchmarkTools.Trial: 
  memory estimate:  312.66 KiB
  allocs estimate:  4
  --------------
  minimum time:     190.424 ms (0.00% GC)
  median time:      194.996 ms (0.00% GC)
  mean time:        196.338 ms (0.00% GC)
  maximum time:     210.910 ms (0.00% GC)
  --------------
  samples:          26
  evals/sample:     1

In [34]:
n = 3
W = rand(0:2,n,n)

3×3 Array{Int64,2}:
 2  1  2
 1  0  1
 2  2  2

In [36]:
x1 = [1, 1, 1]

3-element Array{Int64,1}:
 1
 1
 1

In [37]:
x2 = [0, 0, 1]

3-element Array{Int64,1}:
 0
 0
 1

In [38]:
[W*x1, W*x2]

2-element Array{Array{Int64,1},1}:
 [5, 2, 6]
 [2, 1, 2]

In [39]:
W*[x1 x2]

3×2 Array{Int64,2}:
 5  2
 2  1
 6  2

In [43]:
f = x->W*x
f.([x1,x2])

2-element Array{Array{Int64,1},1}:
 [5, 2, 6]
 [2, 1, 2]

In [46]:
m = Dense(identity,W,zeros(3))

Dense(3, 3)

In [49]:
m.([x1,x2])

2-element Array{Array{Float64,1},1}:
 [5.0, 2.0, 6.0]
 [2.0, 1.0, 2.0]

## to start out

In [54]:
w = [1 1 1]

1×3 Array{Int64,2}:
 1  1  1

In [55]:
m = Dense(identity,w,0)

Dense(3, 1)

In [56]:
m([1,1,1])

1-element Array{Int64,1}:
 3

In [57]:
# w is unknown

In [64]:
x1 = rand(3); y1=m(x1)

1-element Array{Float64,1}:
 1.44698

In [65]:
x2 = rand(3); y2=m(x2)

1-element Array{Float64,1}:
 0.934213

In [66]:
x3 = rand(3); y3=m(x3)

1-element Array{Float64,1}:
 1.50619

In [71]:
[x1 x2 x3]'\[y1[1], y2[1], y3[1]]

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [98]:
X=[x1 x2 x3]

3×3 Array{Float64,2}:
 0.762243  0.143106  0.0635331
 0.653596  0.395324  0.442801 
 0.03114   0.395783  0.99986  

In [102]:
y=[y1; y2; y3]

3-element Array{Float64,1}:
 1.44698 
 0.934213
 1.50619 

In [ ]:
## in the real world, we use gradient descent to find the parameters w

In [136]:
loss(x,y) = Flux.mse(m(x),y)

loss (generic function with 1 method)

In [137]:
@which Flux.mse(rand(3),rand(3))

mse(ŷ, y) in Flux at /Users/edelman/.julia/v0.6/Flux/src/layers/stateless.jl:5

In [138]:
Flux.train!(loss, (X,y))

LoadError: MethodError: no method matching train!(::#loss, ::Tuple{Array{Float64,2},Array{Float64,1}})
Closest candidates are:
  train!(::Any, ::Any, ::Any; cb) at /Users/edelman/.julia/v0.6/Flux/src/optimise/train.jl:26

In [139]:
[x1 x2 x3]

3×3 Array{Float64,2}:
 0.762243  0.143106  0.0635331
 0.653596  0.395324  0.442801 
 0.03114   0.395783  0.99986  

In [140]:
m = Dense(3,1)

Dense(3, 1)

In [141]:
opt = ADAM(Flux.params(m))

(::#71) (generic function with 1 method)

In [142]:
m.W

Tracked 1×3 Array{Float64,2}:
 -0.681719  -0.944965  0.0748232

In [143]:
y1=m(x1).data

1-element Array{Float64,1}:
 -1.13493

In [144]:
y2=m(x2).data

1-element Array{Float64,1}:
 -0.441511

In [145]:
y3=m(x3).data

1-element Array{Float64,1}:
 -0.38693

In [154]:
y1

1-element Array{Float64,1}:
 -1.13493

In [156]:
Flux.train!(loss, Iterators.repeated(([x1,x2,x3],[y1 y2 y3]),3),opt)

LoadError: MethodError: no method matching ForwardDiff.Dual{Void,V,N} where N where V<:Real(::Array{Float64,1}, ::Tuple{Bool,Bool})

In [259]:
# m ... a model we think of as known to nature but not to humans
m = Dense(3,1)
println( (m.W).data,": <== neuron we want to learn" )

# We will learn from data inputs (the columns of X) and outputs (the elements of y)
X = rand(3,3)
y = m(X).data
println( y/X, ": <== learned through Gaussian elimination" )

# t ... a model to be learned to fit the data
t = Dense(3,1)
println((m2.W).data,"  : <== guess before training")
loss(x,y) = Flux.mse(t(x),y)
opt = ADAM(Flux.params(t)[1:1])
Flux.train!(loss, Iterators.repeated( (X,y), 10000), opt)
println((t.W).data, " : <== estimate after training")

[-0.176205 -0.266556 -0.912634]: <== neuron we want to learn
[-0.176205 -0.266556 -0.912634]: <== learned through Gaussian elimination
[0.192249 0.42685 -1.10904]  : <== guess before training
[-0.175004 -0.267848 -0.912096] : <== estimate after training


In [221]:
Flux.params(m2)

2-element Array{Any,1}:
 param([-0.789284 -1.05581 0.135877])
 param([0.0])                        

In [199]:
XX

3×3 Array{Float64,2}:
 0.0639266  0.876013  0.805099
 0.456432   0.456653  0.81204 
 0.745263   0.462979  0.485439

In [200]:
m(XX)

Tracked 1×3 Array{Float64,2}:
 -0.337421  -0.0191289  0.252926

In [201]:
y

3-element Array{Array{Float64,1},1}:
 [-0.337421] 
 [-0.0191289]
 [0.252926]  