## Four ways to multiply $AB = C$ in Julia.

This exercise aims to introduce you to arrays (matrices and vectors) in Julia, and show you some ways to manipulate their rows and columns (called array slicing).

It will also challenge you to think about the four ways to multiply two matrices!

Let's define two matrices $A$ and $B$. $A$ will be $3\times 2$ and $B$ will be $2\times 4$.


In [73]:
A = [1 1 ; 2 1; -1 2; -2 2]

4×2 Matrix{Int64}:
  1  1
  2  1
 -1  2
 -2  2

In [74]:
B = [1 0 -1 -2; 1 1 0 0]

2×4 Matrix{Int64}:
 1  0  -1  -2
 1  1   0   0

What is the matrix $C = AB$? In Julia, matrix-matrix multiplication is performed with `C = A * B`.

In [75]:
C = A*B

4×4 Matrix{Int64}:
 2  1  -1  -2
 3  1  -2  -4
 1  2   1   2
 0  2   2   4

Now, let's explore the four ways to multiply $AB = C$ (textbook pg. 35).

**Method 1: Dot product way.** (Row $i$ of $A$) $\cdot$ (Column $k$ of $B$) = (Number $C_{ik}$)

(Note: The notation `A[i,:]` extracts the $i^{th}$ row of $A$ as a *column vector* in Julia. Use `A[i,:]'` to turn it back into a row vector.)

In [76]:
C1 = zeros(4,4)
for i in 1:4                                # loop over rows of A
    for k in 1:4                            # loop over columns of B
        C1[i,k] = A[i,:]'*B[:,k]            # dot product of row i and column k
    end
end
display(C1)

4×4 Matrix{Float64}:
 2.0  1.0  -1.0  -2.0
 3.0  1.0  -2.0  -4.0
 1.0  2.0   1.0   2.0
 0.0  2.0   2.0   4.0

**Method 2: Column way.** $A \,\times$ (Column $k$ of $B$) = (Column $k$ of $C$)

In [77]:
C2 = zeros(4,4)
for k in 1:4                # loop over columns of B
    C2[:,k] = A*B[:,k]      # A times column k of B
end
display(C2)

4×4 Matrix{Float64}:
 2.0  1.0  -1.0  -2.0
 3.0  1.0  -2.0  -4.0
 1.0  2.0   1.0   2.0
 0.0  2.0   2.0   4.0

**Method 3: Row way.** (Row $i$ of $A$) $\times$ $B$ = (Row $i$ of $C$)

(Note: The notation `A[i,:]` extracts the $i^{th}$ row of $A$ as a *column vector* in Julia. Use `A[i,:]'` to turn it back into a row vector.)

In [78]:
C3 = zeros(4,4)
for i in 1:4                # loop over rows of A
    C3[i,:] = A[i,:]'*B     # row i of A times B
end
display(C3)

4×4 Matrix{Float64}:
 2.0  1.0  -1.0  -2.0
 3.0  1.0  -2.0  -4.0
 1.0  2.0   1.0   2.0
 0.0  2.0   2.0   4.0

**Method 4: Columns times rows.** (Column $j$ of $A$) $\times$ (Row $j$ of $B$) = (Rank 1 matrix). The sum of the rank 1 matrices is $C$.

(Note: The notation `A[i,:]` extracts the $i^{th}$ row of $A$ as a *column vector* in Julia. Use `A[i,:]'` to turn it back into a row vector.)

In [79]:
C4 = zeros(4,4)
for j in 1:4                    # loop over rows of A and columns of B
    C4 = A[j,:]'*B[:,j]         # add row i of A times column j of B
end
display(C3)

4×4 Matrix{Float64}:
 2.0  1.0  -1.0  -2.0
 3.0  1.0  -2.0  -4.0
 1.0  2.0   1.0   2.0
 0.0  2.0   2.0   4.0