In [1]:
using LinearAlgebra

In [84]:
function fullsvd(A) 
    U,s,V = svd(A, full = true)  # compute svd
    Σ = zeros(size(A))           # container for Σ  
    for i=1:length(s)
       Σ[i,i] = s[i]            # place singular values in Σ
    end
    display(U);display(Σ);display(V) # display the answer
    return(U,Σ,V)                # return the answer
end


function rankrsvd(A) 
    U,s,V = svd(A, full = true)  # compute svd
    r = sum(s.>1e-8)             # rank = how many positive?
    U₁ = U[:,1:r]
    Σᵣ = zeros(r,r)
    for i=1:r,  Σᵣ[i,i]=s[i];end
    V₁ = V[:,1:r]
    display(U₁);display(Σᵣ);display(V₁) # display the answer
    return(U₁,Σᵣ,V₁)                # return the answer
end

rankrsvd (generic function with 1 method)

## 1. random 2x2 matrix

In [85]:
A = rand(2,2)

2×2 Array{Float64,2}:
 0.62747   0.6356   
 0.697816  0.0925931

In [86]:
fullsvd(A);

2×2 Array{Float64,2}:
 -0.803436  -0.595391
 -0.595391   0.803436

2×2 Array{Float64,2}:
 1.07972  0.0     
 0.0      0.356974

2×2 Adjoint{Float64,Array{Float64,2}}:
 -0.851707   0.524018
 -0.524018  -0.851707

In [87]:
rankrsvd(A);

2×2 Array{Float64,2}:
 -0.803436  -0.595391
 -0.595391   0.803436

2×2 Array{Float64,2}:
 1.07972  0.0     
 0.0      0.356974

2×2 Array{Float64,2}:
 -0.851707   0.524018
 -0.524018  -0.851707

## 2. random 3x2 matrix

In [88]:
A = rand(3,2)

3×2 Array{Float64,2}:
 0.481367  0.273997
 0.609206  0.683061
 0.433901  0.25777 

In [89]:
fullsvd(A);

3×3 Array{Float64,2}:
 -0.46459    0.599005  -0.652188 
 -0.776959  -0.629081  -0.0243114
 -0.424842   0.495428   0.757668 

3×2 Array{Float64,2}:
 1.16867  0.0     
 0.0      0.182823
 0.0      0.0     

2×2 Adjoint{Float64,Array{Float64,2}}:
 -0.754112   0.656746
 -0.656746  -0.754112

In [90]:
rankrsvd(A);

3×2 Array{Float64,2}:
 -0.46459    0.599005
 -0.776959  -0.629081
 -0.424842   0.495428

2×2 Array{Float64,2}:
 1.16867  0.0     
 0.0      0.182823

2×2 Array{Float64,2}:
 -0.754112   0.656746
 -0.656746  -0.754112

## 3. random 2x3 matrix

In [91]:
A = rand(2,3)

2×3 Array{Float64,2}:
 0.450421  0.261512  0.442317
 0.291175  0.788014  0.895581

In [92]:
fullsvd(A);

2×2 Array{Float64,2}:
 -0.458938  -0.888468
 -0.888468   0.458938

2×3 Array{Float64,2}:
 1.37355  0.0       0.0
 0.0      0.296809  0.0

3×3 Adjoint{Float64,Array{Float64,2}}:
 -0.338842  -0.898062   -0.280481
 -0.597099   0.435652   -0.673558
 -0.727089   0.0607546   0.683849

In [93]:
rankrsvd(A);

2×2 Array{Float64,2}:
 -0.458938  -0.888468
 -0.888468   0.458938

2×2 Array{Float64,2}:
 1.37355  0.0     
 0.0      0.296809

3×2 Array{Float64,2}:
 -0.338842  -0.898062 
 -0.597099   0.435652 
 -0.727089   0.0607546

## 4. rank 3, 7x10 matrix

In [94]:
A = rand(7,3)*rand(3,10) # this should be rank 3

7×10 Array{Float64,2}:
 0.675099  1.21178   0.540798  0.851897  …  0.980326  1.12255   0.413004
 0.789079  0.992535  0.274757  0.82396      0.810722  0.774411  0.379436
 0.344989  0.433055  0.123167  0.362714     0.350748  0.330489  0.163391
 0.5881    0.597549  0.179253  0.627045     0.416998  0.223349  0.191244
 0.505428  0.785696  0.342115  0.618232     0.606376  0.613279  0.255647
 0.368739  0.518505  0.159858  0.396248  …  0.433708  0.458187  0.199473
 0.33104   0.758602  0.461593  0.52759      0.564867  0.652752  0.207733

In [95]:
fullsvd(A);

7×7 Array{Float64,2}:
 -0.592724  -0.418143     0.112732  …   0.381819    0.444132    -0.0645691
 -0.474174   0.309821     0.468304     -0.190313    0.172813    -0.0445874
 -0.205343   0.147727     0.168969     -0.489593   -0.00367499   0.679052 
 -0.242406   0.762887    -0.446661      0.359006    0.0967758    0.0361449
 -0.365226   0.0270369   -0.201379     -0.530609   -0.256068    -0.634402 
 -0.255638   0.00074241   0.316456  …   0.40012    -0.813966     0.0749404
 -0.352378  -0.35301     -0.631846     -0.0881339  -0.188128     0.351202 

7×10 Array{Float64,2}:
 5.17927  0.0       0.0       0.0         …  0.0          0.0  0.0  0.0
 0.0      0.576595  0.0       0.0            0.0          0.0  0.0  0.0
 0.0      0.0       0.237427  0.0            0.0          0.0  0.0  0.0
 0.0      0.0       0.0       2.4823e-16     0.0          0.0  0.0  0.0
 0.0      0.0       0.0       0.0            0.0          0.0  0.0  0.0
 0.0      0.0       0.0       0.0         …  0.0          0.0  0.0  0.0
 0.0      0.0       0.0       0.0            7.59678e-17  0.0  0.0  0.0

10×10 Adjoint{Float64,Array{Float64,2}}:
 -0.267068   0.622417    0.197895    …   0.158315   -0.0600846    0.0117973
 -0.407293   0.129173   -0.277027        0.0456813  -0.274878    -0.1277   
 -0.163738  -0.242179   -0.756366        0.0635529   0.360454     0.145308 
 -0.315705   0.454005   -0.292089       -0.508997   -0.00368076   0.0641535
 -0.286501  -0.196281    0.334703       -0.573086    0.218148    -0.206878 
 -0.437112  -0.363607    0.00702444  …   0.0311102  -0.635766     0.0953444
 -0.358791  -0.0160251   0.123278        0.142756    0.523928    -0.314986 
 -0.322435   0.0494501   0.0901991       0.598296    0.105018    -0.126582 
 -0.333195  -0.38806     0.228883       -0.0272591   0.104831     0.162994 
 -0.139438   0.0843314   0.197212        0.0354542   0.206362     0.87443  

In [96]:
rankrsvd(A);

7×3 Array{Float64,2}:
 -0.592724  -0.418143     0.112732
 -0.474174   0.309821     0.468304
 -0.205343   0.147727     0.168969
 -0.242406   0.762887    -0.446661
 -0.365226   0.0270369   -0.201379
 -0.255638   0.00074241   0.316456
 -0.352378  -0.35301     -0.631846

3×3 Array{Float64,2}:
 5.17927  0.0       0.0     
 0.0      0.576595  0.0     
 0.0      0.0       0.237427

10×3 Array{Float64,2}:
 -0.267068   0.622417    0.197895  
 -0.407293   0.129173   -0.277027  
 -0.163738  -0.242179   -0.756366  
 -0.315705   0.454005   -0.292089  
 -0.286501  -0.196281    0.334703  
 -0.437112  -0.363607    0.00702444
 -0.358791  -0.0160251   0.123278  
 -0.322435   0.0494501   0.0901991 
 -0.333195  -0.38806     0.228883  
 -0.139438   0.0843314   0.197212  