In [1]:
using LinearAlgebra

In [51]:
function fullsvd(A) 
    U,s,V = svd(A, full = true)  # compute svd
    Σ = Diagonal(s)              # create diagonal matrix
    display(U);display(Σ);display(V) # display the answer
    return(U,Σ,V)                # return the answer
end


function rankrsvd(A) 
    U,s,V = svd(A, full = true)  # compute svd
    r = sum(s.>1e-8)                # how many positive?
    U₁ = U[:,1:r]
    Σᵣ = zeros(size(A))
    for i=1:r,  Σᵣ[i,i]=s[i];end
    V₁ = V[:,1:r]
    display(U₁);display(Σᵣ);display(V₁) # display the answer
    return(U₁,Σᵣ,V₁)                # return the answer
end

rankrsvd (generic function with 1 method)

## 1. random 2x2 matrix

In [52]:
A = rand(2,2)

2×2 Array{Float64,2}:
 0.430456  0.0791978
 0.378891  0.108732 

In [53]:
fullsvd(A);

2×2 Array{Float64,2}:
 -0.743231  -0.669035
 -0.669035   0.743231

2×2 Diagonal{Float64,Array{Float64,1}}:
 0.588329   ⋅       
  ⋅        0.0285503

2×2 Adjoint{Float64,Array{Float64,2}}:
 -0.974659  -0.223698
 -0.223698   0.974659

In [54]:
rankrsvd(A);

2×2 Array{Float64,2}:
 -0.743231  -0.669035
 -0.669035   0.743231

2×2 Array{Float64,2}:
 0.588329  0.0      
 0.0       0.0285503

2×2 Array{Float64,2}:
 -0.974659  -0.223698
 -0.223698   0.974659

## 2. random 3x2 matrix

In [55]:
A = rand(3,2)

3×2 Array{Float64,2}:
 0.656842  0.689149
 0.709886  0.038647
 0.976548  0.197604

In [56]:
fullsvd(A);

3×3 Array{Float64,2}:
 -0.590491   0.794436  -0.142094
 -0.456709  -0.474104  -0.752757
 -0.665385  -0.379601   0.64278 

2×2 Diagonal{Float64,Array{Float64,1}}:
 1.471   ⋅      
  ⋅     0.490552

2×2 Adjoint{Float64,Array{Float64,2}}:
 -0.925797  -0.378021
 -0.378021   0.925797

In [57]:
rankrsvd(A);

3×2 Array{Float64,2}:
 -0.590491   0.794436
 -0.456709  -0.474104
 -0.665385  -0.379601

3×2 Array{Float64,2}:
 1.471  0.0     
 0.0    0.490552
 0.0    0.0     

2×2 Array{Float64,2}:
 -0.925797  -0.378021
 -0.378021   0.925797

## 3. random 2x3 matrix

In [58]:
A = rand(2,3)

2×3 Array{Float64,2}:
 0.880263  0.581473  0.63899 
 0.980413  0.140558  0.283384

In [59]:
fullsvd(A);

2×2 Array{Float64,2}:
 -0.774649  -0.632391
 -0.632391   0.774649

2×2 Diagonal{Float64,Array{Float64,1}}:
 1.56217   ⋅      
  ⋅       0.377082

3×3 Adjoint{Float64,Array{Float64,2}}:
 -0.833394   0.537829  -0.12726 
 -0.345242  -0.686414  -0.640034
 -0.431582  -0.489465   0.757735

In [60]:
rankrsvd(A);

2×2 Array{Float64,2}:
 -0.774649  -0.632391
 -0.632391   0.774649

2×3 Array{Float64,2}:
 1.56217  0.0       0.0
 0.0      0.377082  0.0

3×2 Array{Float64,2}:
 -0.833394   0.537829
 -0.345242  -0.686414
 -0.431582  -0.489465

## 4. rank 3, 7x10 matrix

In [61]:
A = rand(7,3)*rand(3,10) # this should be rank 3

7×10 Array{Float64,2}:
 0.930672  2.35675   0.965621  0.823958  …  1.4458    1.62409   1.29048 
 0.315908  0.827526  0.366524  0.315184     0.493389  0.596159  0.450122
 0.769409  1.79242   0.532503  0.446302     1.18626   1.0532    0.978546
 0.365596  1.05974   0.52129   0.462317     0.586578  0.820747  0.545711
 0.580624  1.29765   0.623938  0.484805     0.852198  0.933669  0.842997
 0.648379  1.69982   0.826753  0.701694  …  1.00363   1.28117   0.955619
 0.268488  0.652024  0.177796  0.156791     0.422202  0.376156  0.333613

In [62]:
fullsvd(A);

7×7 Array{Float64,2}:
 -0.594999  -0.0320969   0.183814   …   0.517075  -0.109497   0.280394
 -0.210266  -0.122385    0.0919266      0.062611  -0.699138  -0.646761
 -0.440776   0.725916    0.126282      -0.405822  -0.12681    0.17321 
 -0.269941  -0.433273    0.357454      -0.670699   0.195663  -0.129672
 -0.342771  -0.0122256  -0.876694      -0.153057   0.111462  -0.191944
 -0.438442  -0.446363   -0.0310657  …   0.107589   0.175752   0.206312
 -0.157763   0.26443     0.21091        0.281394   0.633671  -0.613886

7×7 Diagonal{Float64,Array{Float64,1}}:
 8.16895   ⋅         ⋅         ⋅           …   ⋅            ⋅         
  ⋅       0.454117   ⋅         ⋅               ⋅            ⋅         
  ⋅        ⋅        0.267467   ⋅               ⋅            ⋅         
  ⋅        ⋅         ⋅        4.92228e-16      ⋅            ⋅         
  ⋅        ⋅         ⋅         ⋅               ⋅            ⋅         
  ⋅        ⋅         ⋅         ⋅           …  1.20117e-16   ⋅         
  ⋅        ⋅         ⋅         ⋅               ⋅           9.57633e-17

10×10 Adjoint{Float64,Array{Float64,2}}:
 -0.193863   0.233586   -0.166706    …  -0.0740145   0.152865   -0.00736664
 -0.482966   0.138467    0.229937        0.0941578  -0.483474    0.207729  
 -0.199713  -0.539075   -0.263273        0.552687   -0.252394   -0.0515281 
 -0.168517  -0.482316   -0.0437798      -0.339925   -0.352867   -0.0622758 
 -0.454474   0.0161877   0.0240535      -0.287339    0.254391    0.138186  
 -0.382142   0.120008    0.551107    …  -0.105996   -0.104377   -0.323911  
 -0.188155   0.276204   -0.629222       -0.233368   -0.20856    -0.571354  
 -0.299176   0.337864   -0.0697575       0.624794    0.195323   -0.07223   
 -0.332792  -0.440364    0.00263416     -0.0427379   0.629451   -0.207675  
 -0.269518   0.063311   -0.378177       -0.155535    0.0346519   0.671905  

In [63]:
rankrsvd(A);

7×3 Array{Float64,2}:
 -0.594999  -0.0320969   0.183814 
 -0.210266  -0.122385    0.0919266
 -0.440776   0.725916    0.126282 
 -0.269941  -0.433273    0.357454 
 -0.342771  -0.0122256  -0.876694 
 -0.438442  -0.446363   -0.0310657
 -0.157763   0.26443     0.21091  

7×10 Array{Float64,2}:
 8.16895  0.0       0.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0      0.454117  0.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0      0.0       0.267467  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0      0.0       0.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0      0.0       0.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0      0.0       0.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0      0.0       0.0       0.0  0.0  0.0  0.0  0.0  0.0  0.0

10×3 Array{Float64,2}:
 -0.193863   0.233586   -0.166706  
 -0.482966   0.138467    0.229937  
 -0.199713  -0.539075   -0.263273  
 -0.168517  -0.482316   -0.0437798 
 -0.454474   0.0161877   0.0240535 
 -0.382142   0.120008    0.551107  
 -0.188155   0.276204   -0.629222  
 -0.299176   0.337864   -0.0697575 
 -0.332792  -0.440364    0.00263416
 -0.269518   0.063311   -0.378177  